# Generated by Django 4.2.14 on 2024-07-24 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('name', models.CharField(choices=[('A', 'Class A'), ('B', 'Class B')], max_length=1, primary_key=True, serialize=False)),
                ('room_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.ForeignKey(default='A', on_delete=django.db.models.deletion.CASCADE, to='main.roomtype'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, to='main.roomtype'),
            preserve_default=False,
        ),
    ]
