# Generated by Django 4.2.14 on 2024-07-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_payment_mpesa_code_alter_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
