# Generated by Django 4.2.14 on 2024-07-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='manual_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
