# Generated by Django 4.2.14 on 2024-07-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_guest_manual_id_alter_guest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='payment_method',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='manual_id',
            field=models.IntegerField(default=True),
        ),
    ]
