# Generated by Django 4.2.14 on 2024-07-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_guest_payment_method_alter_guest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='manual_id',
            field=models.CharField(max_length=20),
        ),
    ]
